apiVersion: v1 
kind: Service
metadata:
   name: postgres-service
   namespace: sonarqube-namespace
   labels: 
     app: postgres-service
spec:
   ports:
   - port: 5432
     targetPort: 5432
   selector: 
     app: sonarqube-database

# kubectl port-forward svc/sonarqube-service 9000:9000 -n sonarqube-namespace
