apiVersion: v1 
kind: PersistentVolume
metadata:
   name: sonarqube-data-pv
   namespace: sonarqube-namespace
spec:
   storageClassName: sonarqube-data-pv
   accessModes:
   - ReadWriteOnce
   capacity:
      storage: 20Gi
   persistentVolumeReclaimPolicy: Retain
   hostPath: 
      path: /root/k8s-resource-sonarqube/folder_container/sonarqube/
