apiVersion: v1 
kind: PersistentVolume
metadata:
  name: sonarqube-postgres-pv
  namespace: sonarqube-namespace
spec: 
  storageClassName: sonarqube-postgres-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /home/kube/folder_container/postgres/
