apiVersion: v1
kind: ConfigMap
metadata: 
  name: configmap-for-sonarqube
  namespace: sonarqube-namespace
  labels:
    app: sonarqube
data: 
  SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres-service:5432/sonar_db"
  SONARQUBE_JDBC_USERNAME: "sonar_user"
  SONARQUBE_JDBC_DRIVER: "oracle.jdbc.OracleDriver"
  JAVA_OPTS: "-Duser.timezone=Europe/Madrid -Xmx2048m"

