apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
  namespace: monitoring
spec:
  storageClassName: azure-disk
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
        storage: 10Gi
