apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgres-pvc
  namespace: sonarqube-namespace
spec:
  storageClassName: sonarqube-postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 10Gi
